# Generated by Django 5.0.6 on 2025-12-03 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdBirdsong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('0', 'Not Started'), ('1', 'Emergency drawing'), ('2', 'Add to Decree'), ('3', 'Emergency roosting'), ('4', 'Completed')], default='0', max_length=1)),
                ('cards_drawn', models.IntegerField(default=0)),
                ('cards_added_to_decree', models.IntegerField(default=0)),
                ('bird_card_added_to_decree', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BirdDaylight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('0', 'Not Started'), ('1', 'Crafting'), ('2', 'Recruiting'), ('3', 'Moving'), ('4', 'Battling'), ('5', 'Building'), ('6', 'Completed'), ('a', 'Humiliate'), ('b', 'Purge'), ('c', 'Depose')], default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BirdEvening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('0', 'Not Started'), ('1', 'Scoring'), ('2', 'Drawing Cards'), ('3', 'Discarding Cards'), ('4', 'Completed')], default='0', max_length=1)),
                ('cards_drawn', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(choices=[('r', 'Fox'), ('y', 'Rabbit'), ('o', 'Mouse'), ('b', 'Bird')], max_length=1)),
                ('card_type', models.CharField(choices=[('SABOTEURS', 'SABOTEURS'), ('SOUP_KITCHENS', 'SOUP_KITCHENS'), ('BOAT_BUILDERS', 'BOAT_BUILDERS'), ('CORVID_PLANNERS', 'CORVID_PLANNERS'), ('EYRIE_EMIGRE', 'EYRIE_EMIGRE'), ('INFORMANTS', 'INFORMANTS'), ('RABBIT_PARTISANS', 'RABBIT_PARTISANS'), ('TUNNELS', 'TUNNELS'), ('CHARM_OFFENSIVE', 'CHARM_OFFENSIVE'), ('LEAGUE_OF_ADVENTURERS', 'LEAGUE_OF_ADVENTURERS'), ('MURINE_BROKERS', 'MURINE_BROKERS'), ('MASTER_ENGRAVERS', 'MASTER_ENGRAVERS'), ('TRAVEL_GEAR_RED', 'TRAVEL_GEAR_RED'), ('PROTECTION_RACKET', 'PROTECTION_RACKET'), ('FOXFOLK_STEEL', 'FOXFOLK_STEEL'), ('ANVIL', 'ANVIL'), ('BIRDY_BINDLE', 'BIRDY_BINDLE'), ('TRAVEL_GEAR_ORANGE', 'TRAVEL_GEAR_ORANGE'), ('ROOT_TEA_ORANGE', 'ROOT_TEA_ORANGE'), ('MOUSE_IN_A_SACK', 'MOUSE_IN_A_SACK'), ('SWORD', 'SWORD'), ('CROSSBOW_ORANGE', 'CROSSBOW_ORANGE'), ('DOMINANCE_WILD', 'DOMINANCE_WILD'), ('DOMINANCE_RED', 'DOMINANCE_RED'), ('DOMINANCE_YELLOW', 'DOMINANCE_YELLOW'), ('DOMINANCE_ORANGE', 'DOMINANCE_ORANGE'), ('FOX_PARTISANS', 'FOX_PARTISANS'), ('PROPAGANDA_BUREAU', 'PROPAGANDA_BUREAU'), ('FALSE_ORDERS', 'FALSE_ORDERS'), ('COFFIN_MAKERS', 'COFFIN_MAKERS'), ('SWAP_MEET', 'SWAP_MEET'), ('MOUSE_PARTISANS', 'MOUSE_PARTISANS'), ('WOODLAND_RUNNERS', 'WOODLAND_RUNNERS'), ('ARMS_TRADER', 'ARMS_TRADER'), ('CROSSBOW_WILD', 'CROSSBOW_WILD'), ('GENTLY_USED_KNAPSACK', 'GENTLY_USED_KNAPSACK'), ('ROOT_TEA_RED', 'ROOT_TEA_RED'), ('SMUGGLERS_TRAIL', 'SMUGGLERS_TRAIL'), ('ROOT_TEA_YELLOW', 'ROOT_TEA_YELLOW'), ('A_VISIT_TO_FRIENDS', 'A_VISIT_TO_FRIENDS'), ('BAKE_SALE', 'BAKE_SALE'), ('INVESTMENTS', 'INVESTMENTS'), ('AMBUSH_RED', 'AMBUSH_RED'), ('AMBUSH_YELLOW', 'AMBUSH_YELLOW'), ('AMBUSH_ORANGE', 'AMBUSH_ORANGE'), ('AMBUSH_WILD', 'AMBUSH_WILD')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CatTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('battle', 'Battle'), ('field_hospital', 'Field Hospital')], max_length=50)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WABirdsong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('0', 'Not Started'), ('1', 'Revolt'), ('2', 'Spread Sympathy'), ('3', 'Completed')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='WADaylight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('0', 'Not Started'), ('1', 'Crafting'), ('2', 'Mobilizing'), ('3', 'Training'), ('4', 'Completed')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='WAEvening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('0', 'Not Started'), ('1', 'Military Operations'), ('2', 'Drawing Cards'), ('3', 'Discarding Cards'), ('4', 'Completed')], max_length=1)),
                ('operations_perfomed', models.IntegerField(default=0)),
                ('cards_drawn', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.piece')),
            ],
            bases=('game.piece',),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.piece')),
            ],
            bases=('game.piece',),
        ),
        migrations.CreateModel(
            name='Warrior',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.piece')),
            ],
            bases=('game.piece',),
        ),
        migrations.CreateModel(
            name='CatEvening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('1', 'Drawing Cards'), ('2', 'Discarding Cards'), ('3', 'Completed')], default='1', max_length=1)),
                ('cards_drawn', models.IntegerField(default=0)),
                ('turn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evening', to='game.catturn')),
            ],
        ),
        migrations.CreateModel(
            name='CatDaylight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('1', 'Crafting'), ('2', 'Actions'), ('3', 'Completed')], default='1', max_length=1)),
                ('actions_left', models.IntegerField(default=3)),
                ('recruit_used', models.BooleanField(default=False)),
                ('midmarch', models.BooleanField(default=False)),
                ('turn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daylight', to='game.catturn')),
            ],
        ),
        migrations.CreateModel(
            name='CatBirdsong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('1', 'Place wood'), ('3', 'Completed')], default='1', max_length=1)),
                ('turn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birdsong', to='game.catturn')),
            ],
        ),
        migrations.CreateModel(
            name='Clearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearing_number', models.PositiveSmallIntegerField()),
                ('suit', models.CharField(choices=[('r', 'Fox'), ('y', 'Rabbit'), ('o', 'Mouse'), ('b', 'Bird')], max_length=1)),
                ('connected_clearings', models.ManyToManyField(related_name='+', to='game.clearing')),
                ('water_connected_clearings', models.ManyToManyField(related_name='+', to='game.clearing')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_slot_number', models.PositiveSmallIntegerField()),
                ('clearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.clearing')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker', models.CharField(choices=[('ca', 'Cats'), ('bi', 'Birds'), ('wa', 'Woodland Alliance')], max_length=2)),
                ('defender', models.CharField(choices=[('ca', 'Cats'), ('bi', 'Birds'), ('wa', 'Woodland Alliance')], max_length=2)),
                ('step', models.CharField(choices=[('0', 'Not Started'), ('1', 'Defender Ambush'), ('2', 'Attacker Ambush'), ('3', 'Attacker Chooses Ambush Hits'), ('4', 'Roll Dice'), ('5', 'Defender Chooses Hits'), ('6', 'Attacker Chooses Hits'), ('7', 'Completed')], default='0', max_length=1)),
                ('defender_ambush', models.BooleanField(default=False)),
                ('attacker_cancel_ambush', models.BooleanField(default=False)),
                ('attacker_ambush_hits_taken', models.PositiveSmallIntegerField(default=0)),
                ('attacker_ambush_hits_assigned', models.PositiveSmallIntegerField(default=0)),
                ('defender_hits_taken', models.PositiveSmallIntegerField(default=0)),
                ('defender_hits_assigned', models.PositiveSmallIntegerField(default=0)),
                ('attacker_hits_taken', models.PositiveSmallIntegerField(default=0)),
                ('attacker_hits_assigned', models.PositiveSmallIntegerField(default=0)),
                ('clearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.clearing')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battle', to='game.event')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardmap', models.CharField(choices=[('0', 'Autumn'), ('1', 'Winter'), ('2', 'Mountain'), ('3', 'Lake')], max_length=1)),
                ('status', models.CharField(choices=[('0', 'Not Started'), ('1', 'Started'), ('2', 'Setup Completed'), ('3', 'Completed')], default='0', max_length=1)),
                ('current_turn', models.PositiveSmallIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FactionChoiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction', models.CharField(choices=[('ca', 'Cats'), ('bi', 'Birds'), ('wa', 'Woodland Alliance')], max_length=2)),
                ('chosen', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.CreateModel(
            name='DiscardPileEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.PositiveSmallIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
            options={
                'ordering': ['spot'],
            },
        ),
        migrations.CreateModel(
            name='DeckEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.PositiveSmallIntegerField()),
                ('card', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='game.card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
            options={
                'ordering': ['spot'],
            },
        ),
        migrations.AddField(
            model_name='clearing',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AddField(
            model_name='card',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.CreateModel(
            name='GameSimpleSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Initial Setup'), ('a', 'Cats Setup'), ('b', 'Birds Setup'), ('2', 'All Setup Completed')], default='0', max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_setup', to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('0', 'Boots'), ('1', 'Bag'), ('2', 'Crossbow'), ('3', 'Hammer'), ('4', 'Sword'), ('5', 'Tea'), ('6', 'Coin')], max_length=1)),
                ('exhausted', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='CraftableItemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction', models.CharField(choices=[('ca', 'Cats'), ('bi', 'Birds'), ('wa', 'Woodland Alliance')], max_length=2, null=True)),
                ('score', models.IntegerField(default=0)),
                ('turn_order', models.PositiveSmallIntegerField(default=None, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
        migrations.CreateModel(
            name='HandEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='FieldHospitalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('troops_To_save', models.IntegerField(default=0)),
                ('suit', models.CharField(choices=[('r', 'Fox'), ('y', 'Rabbit'), ('o', 'Mouse'), ('b', 'Bird')], max_length=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='DecreeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('R', 'Recruit'), ('M', 'Move'), ('B', 'Battle'), ('U', 'Build')], max_length=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decree_entries', to='game.player')),
            ],
            options={
                'ordering': ['column', 'card__suit'],
            },
        ),
        migrations.CreateModel(
            name='CraftedItemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='CraftedCardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crafted_cards', to='game.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.AddField(
            model_name='catturn',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
        migrations.CreateModel(
            name='CatsSimpleSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('1', 'Picking Corner'), ('2', 'Placing Buildings'), ('3', 'Pending Confirmation'), ('4', 'Completed')], default='1', max_length=1)),
                ('recruiter_placed', models.BooleanField(default=False)),
                ('sawmill_placed', models.BooleanField(default=False)),
                ('workshop_placed', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='BirdTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveSmallIntegerField()),
                ('birdsong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.birdbirdsong')),
                ('daylight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.birddaylight')),
                ('evening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.birdevening')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='BirdsSimpleSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('1', 'Picking Corner'), ('2', 'Choosing Leader'), ('3', 'Pending Confirmation'), ('4', 'Completed')], default='1', max_length=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='BirdLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.CharField(choices=[('0', 'Builder'), ('1', 'Charismatic'), ('2', 'Commander'), ('3', 'Despot')], max_length=1)),
                ('available', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='Ruin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.buildingslot')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
            ],
        ),
        migrations.CreateModel(
            name='SupporterStackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporter_stack_entries', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='WATurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveSmallIntegerField()),
                ('birdsong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.wabirdsong')),
                ('daylight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.wadaylight')),
                ('evening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.waevening')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='BirdRoost',
            fields=[
                ('building_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.building')),
                ('crafted_with', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('game.building', models.Model),
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('building_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.building')),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('game.building',),
        ),
        migrations.CreateModel(
            name='Sawmill',
            fields=[
                ('building_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.building')),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('game.building',),
        ),
        migrations.CreateModel(
            name='WABase',
            fields=[
                ('building_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.building')),
                ('suit', models.CharField(choices=[('r', 'Fox'), ('y', 'Rabbit'), ('o', 'Mouse'), ('b', 'Bird')], max_length=1)),
            ],
            bases=('game.building',),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('building_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.building')),
                ('crafted_with', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('game.building', models.Model),
        ),
        migrations.AddField(
            model_name='building',
            name='building_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building', to='game.buildingslot', unique=True),
        ),
        migrations.CreateModel(
            name='CatKeep',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.token')),
                ('destroyed', models.BooleanField(default=False)),
            ],
            bases=('game.token',),
        ),
        migrations.CreateModel(
            name='CatWood',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.token')),
            ],
            bases=('game.token',),
        ),
        migrations.CreateModel(
            name='WASympathy',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.token')),
                ('crafted_with', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('game.token', models.Model),
        ),
        migrations.AddField(
            model_name='token',
            name='clearing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.clearing'),
        ),
        migrations.CreateModel(
            name='WarriorSupplyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warrior_supply_entries', to='game.player')),
                ('warrior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.warrior')),
            ],
        ),
        migrations.AddField(
            model_name='warrior',
            name='clearing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.clearing'),
        ),
        migrations.CreateModel(
            name='OfficerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_entries', to='game.player')),
                ('warrior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.warrior')),
            ],
        ),
        migrations.AddConstraint(
            model_name='factionchoiceentry',
            constraint=models.UniqueConstraint(fields=('game', 'faction'), name='unique_faction_choice_per_game'),
        ),
        migrations.AddConstraint(
            model_name='discardpileentry',
            constraint=models.UniqueConstraint(fields=('game', 'spot'), name='unique_discard_pile_spot'),
        ),
        migrations.AddIndex(
            model_name='deckentry',
            index=models.Index(fields=['game', 'spot'], name='game_decken_game_id_f864e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='deckentry',
            constraint=models.UniqueConstraint(fields=('game', 'spot'), name='unique_deck_spot'),
        ),
        migrations.AddConstraint(
            model_name='gamesimplesetup',
            constraint=models.UniqueConstraint(fields=('game',), name='unique_game_setup_per_game'),
        ),
        migrations.AddConstraint(
            model_name='catssimplesetup',
            constraint=models.UniqueConstraint(fields=('player',), name='unique_setup_per_player'),
        ),
    ]
