# Generated by Django 5.0.6 on 2025-10-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decreeentry',
            old_name='bird_player',
            new_name='player',
        ),
    ]
