# Generated by Django 5.0.6 on 2025-12-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catdaylight',
            name='midmarch',
            field=models.BooleanField(default=False),
        ),
    ]
