# Generated by Django 5.0.6 on 2026-01-29 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('battle', 'Battle'), ('field_hospital', 'Field Hospital'), ('turmoil', 'Turmoil'), ('outrage', 'Outrage'), ('informants', 'Informants'), ('saboteurs', 'Saboteurs'), ('eyrie_emigre', 'Eyrie Emigre'), ('charm_offensive', 'Charm Offensive'), ('partisans', 'Partisans'), ('swap_meet', 'Swap Meet')], max_length=50),
        ),
        migrations.CreateModel(
            name='SwapMeetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swap_meet', to='game.event')),
                ('taken_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_meet_taken_cards', to='game.card')),
                ('taken_from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_meet_given_events', to='game.player')),
                ('taking_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_meet_take_events', to='game.player')),
            ],
        ),
    ]
