# Generated by Django 5.0.6 on 2025-12-04 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='step',
            field=models.CharField(choices=[('1', 'Defender Ambush'), ('2', 'Attacker Ambush'), ('3', 'Attacker Chooses Ambush Hits'), ('4', 'Roll Dice'), ('5', 'Defender Chooses Hits'), ('6', 'Attacker Chooses Hits'), ('7', 'Completed')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_slot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building', to='game.buildingslot', unique=True),
        ),
    ]
