# Generated by Django 5.0.6 on 2026-02-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_event_type_swapmeetevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkpoint',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='checkpoint',
            name='unique_checkpoint_per_turn',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='turn_number',
        ),
    ]
