# Generated by Django 5.0.6 on 2025-10-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_bird_player_decreeentry_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decreeentry',
            options={'ordering': ['column', 'card__suit']},
        ),
        migrations.AddField(
            model_name='player',
            name='is_turn',
            field=models.BooleanField(default=False),
        ),
    ]
