# Generated by Django 5.0.6 on 2025-12-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_battle_step_alter_building_building_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdturn',
            name='birdsong',
        ),
        migrations.RemoveField(
            model_name='birdturn',
            name='daylight',
        ),
        migrations.RemoveField(
            model_name='birdturn',
            name='evening',
        ),
        migrations.RemoveField(
            model_name='waturn',
            name='birdsong',
        ),
        migrations.RemoveField(
            model_name='waturn',
            name='daylight',
        ),
        migrations.RemoveField(
            model_name='waturn',
            name='evening',
        ),
        migrations.AddField(
            model_name='birdbirdsong',
            name='turn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.birdturn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birddaylight',
            name='turn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.birdturn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birdevening',
            name='turn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.birdturn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wabirdsong',
            name='turn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.waturn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wadaylight',
            name='turn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.waturn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waevening',
            name='turn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.waturn'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wabirdsong',
            name='step',
            field=models.CharField(choices=[('1', 'Revolt'), ('2', 'Spread Sympathy'), ('3', 'Completed')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='wadaylight',
            name='step',
            field=models.CharField(choices=[('1', 'Crafting'), ('2', 'Mobilizing'), ('3', 'Training'), ('4', 'Completed')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='waevening',
            name='step',
            field=models.CharField(choices=[('1', 'Military Operations'), ('2', 'Drawing Cards'), ('3', 'Discarding Cards'), ('4', 'Completed')], default='1', max_length=1),
        ),
    ]
