# Generated by Django 5.0.6 on 2026-02-15 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_checkpoint_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factionchoiceentry',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_choices', to='game.game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='faction',
            field=models.CharField(blank=True, choices=[('ca', 'Cats'), ('bi', 'Birds'), ('wa', 'Woodland Alliance')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='ActiveDominanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_dominance', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='DominanceSupplyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dominancesupplyentry',
            constraint=models.UniqueConstraint(fields=('game', 'card'), name='unique_dominance_supply_entry'),
        ),
    ]
