# Generated by Django 5.0.6 on 2025-10-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_decreeentry_options_player_is_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Started'), ('2', 'Completed')], default='0', max_length=1),
        ),
    ]
