# Generated by Django 5.0.6 on 2025-12-10 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_birdturn_birdsong_remove_birdturn_daylight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdbirdsong',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birdsong', to='game.birdturn'),
        ),
        migrations.AlterField(
            model_name='birddaylight',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daylight', to='game.birdturn'),
        ),
        migrations.AlterField(
            model_name='birdevening',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evening', to='game.birdturn'),
        ),
    ]
