# Generated by Django 5.0.6 on 2025-10-29 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('0', 'Not Started'), ('1', 'Defender Ambush'), ('2', 'Attacker Ambush'), ('3', 'Attacker Chooses Ambush Hits'), ('4', 'Roll Dice'), ('5', 'Defender Chooses Hits'), ('6', 'Attacker Chooses Hits'), ('7', 'Completed')], default='0', max_length=1)),
                ('defender_ambush', models.BooleanField(default=False)),
                ('attacker_cancel_ambush', models.BooleanField(default=False)),
                ('attacker_ambush_hits_taken', models.PositiveSmallIntegerField(default=0)),
                ('attacker_ambush_hits_assigned', models.PositiveSmallIntegerField(default=0)),
                ('defender_hits_taken', models.PositiveSmallIntegerField(default=0)),
                ('defender_hits_assigned', models.PositiveSmallIntegerField(default=0)),
                ('attacker_hits_taken', models.PositiveSmallIntegerField(default=0)),
                ('attacker_hits_assigned', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='birdssimplesetup',
            name='step',
            field=models.CharField(choices=[('1', 'Picking Corner'), ('2', 'Choosing Leader'), ('3', 'Pending Confirmation'), ('4', 'Completed')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='catssimplesetup',
            name='step',
            field=models.CharField(choices=[('1', 'Picking Corner'), ('2', 'Placing Buildings'), ('3', 'Pending Confirmation'), ('4', 'Completed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Started'), ('2', 'Setup Completed'), ('3', 'Completed')], default='0', max_length=1),
        ),
        migrations.CreateModel(
            name='GameSimpleSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Initial Setup'), ('a', 'Cats Setup'), ('b', 'Birds Setup'), ('c', 'Woodland Alliance Setup'), ('2', 'All Setup Completed')], default='0', max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_setup', to='game.game')),
            ],
        ),
        migrations.AddConstraint(
            model_name='gamesimplesetup',
            constraint=models.UniqueConstraint(fields=('game',), name='unique_game_setup_per_game'),
        ),
    ]
