# Generated by Django 5.0.6 on 2026-02-25 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_factionchoiceentry_game_alter_player_faction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.token')),
                ('crafted_with', models.BooleanField(default=False)),
                ('plot_type', models.CharField(choices=[('bomb', 'Bomb'), ('snare', 'Snare'), ('extortion', 'Extortion'), ('raid', 'Raid')], max_length=15)),
                ('is_facedown', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('game.token', models.Model),
        ),
        migrations.AlterField(
            model_name='wabirdsong',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birdsong', to='game.waturn'),
        ),
        migrations.AlterField(
            model_name='wadaylight',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daylight', to='game.waturn'),
        ),
        migrations.AlterField(
            model_name='waevening',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evening', to='game.waturn'),
        ),
        migrations.CreateModel(
            name='CrowRecruitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crow_recruit', to='game.event')),
            ],
        ),
        migrations.CreateModel(
            name='CrowTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveSmallIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='CrowEvening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('1', 'Exert'), ('2', 'Drawing'), ('3', 'Discarding'), ('4', 'Completed')], default='1', max_length=1)),
                ('cards_drawn', models.IntegerField(default=0)),
                ('exert_used', models.BooleanField(default=False)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evening', to='game.crowturn')),
            ],
        ),
        migrations.CreateModel(
            name='CrowDaylight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('1', 'Actions'), ('2', 'Completed')], default='1', max_length=1)),
                ('actions_remaining', models.IntegerField(default=3)),
                ('plots_placed', models.IntegerField(default=0)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daylight', to='game.crowturn')),
            ],
        ),
        migrations.CreateModel(
            name='CrowBirdsong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('0', 'Not Started'), ('1', 'Craft'), ('2', 'Flip'), ('3', 'Recruit'), ('4', 'Completed')], default='0', max_length=1)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birdsong', to='game.crowturn')),
            ],
        ),
    ]
