# Generated by Django 5.0.6 on 2025-12-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_birdbirdsong_turn_alter_birddaylight_turn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decreeentry',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='birdbirdsong',
            name='step',
            field=models.CharField(choices=[('1', 'Emergency drawing'), ('2', 'Add to Decree'), ('3', 'Emergency roosting'), ('4', 'Completed')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='birddaylight',
            name='step',
            field=models.CharField(choices=[('1', 'Crafting'), ('2', 'Recruiting'), ('3', 'Moving'), ('4', 'Battling'), ('5', 'Building'), ('6', 'Completed'), ('a', 'Humiliate'), ('b', 'Purge'), ('c', 'Depose')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='birdevening',
            name='step',
            field=models.CharField(choices=[('1', 'Scoring'), ('2', 'Drawing Cards'), ('3', 'Discarding Cards'), ('4', 'Completed')], default='1', max_length=1),
        ),
    ]
