# Generated by Django 5.0.6 on 2025-12-12 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_decreeentry_fulfilled_alter_birdbirdsong_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vizier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('R', 'Recruit'), ('M', 'Move'), ('B', 'Battle'), ('U', 'Build')], max_length=1)),
                ('fulfilled', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
            options={
                'ordering': ['column'],
            },
        ),
    ]
