# Generated by Django 5.0.6 on 2025-10-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_battle_alter_birdssimplesetup_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catssimplesetup',
            name='step',
            field=models.CharField(choices=[('1', 'Picking Corner'), ('2', 'Placing Buildings'), ('3', 'Pending Confirmation'), ('4', 'Completed')], default='1', max_length=1),
        ),
    ]
