# Generated by Django 5.0.6 on 2026-02-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_plottoken_alter_wabirdsong_turn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowrecruitevent',
            name='recruited_clearings',
            field=models.ManyToManyField(blank=True, to='game.clearing'),
        ),
        migrations.AddField(
            model_name='crowrecruitevent',
            name='suit',
            field=models.CharField(choices=[('r', 'Fox'), ('y', 'Rabbit'), ('o', 'Mouse'), ('b', 'Bird')], default='r', max_length=1),
            preserve_default=False,
        ),
    ]
