# Generated by Django 5.0.6 on 2026-02-26 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_crowrecruitevent_recruited_clearings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='attacker',
            field=models.CharField(choices=[('ca', 'Cats'), ('bi', 'Birds'), ('wa', 'Woodland Alliance'), ('cr', 'Crows')], max_length=2),
        ),
        migrations.AlterField(
            model_name='battle',
            name='defender',
            field=models.CharField(choices=[('ca', 'Cats'), ('bi', 'Birds'), ('wa', 'Woodland Alliance'), ('cr', 'Crows')], max_length=2),
        ),
        migrations.AlterField(
            model_name='factionchoiceentry',
            name='faction',
            field=models.CharField(choices=[('ca', 'Cats'), ('bi', 'Birds'), ('wa', 'Woodland Alliance'), ('cr', 'Crows')], max_length=2),
        ),
        migrations.AlterField(
            model_name='gamesimplesetup',
            name='status',
            field=models.CharField(choices=[('INIT', 'Initial Setup'), ('CAT', 'Cats Setup'), ('BIRD', 'Birds Setup'), ('WA', 'Woodland Alliance Setup'), ('VB', 'Vagabond Setup'), ('CROW', 'Crows Setup'), ('COMP', 'Completed')], default='INIT', max_length=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='faction',
            field=models.CharField(blank=True, choices=[('ca', 'Cats'), ('bi', 'Birds'), ('wa', 'Woodland Alliance'), ('cr', 'Crows')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='CrowsSimpleSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('1', 'Warrior Place'), ('2', 'Pending Confirmation'), ('3', 'Completed')], default='1', max_length=1)),
                ('fox_placed', models.BooleanField(default=False)),
                ('rabbit_placed', models.BooleanField(default=False)),
                ('mouse_placed', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='crowssimplesetup',
            constraint=models.UniqueConstraint(fields=('player',), name='unique_crows_setup_per_player'),
        ),
    ]
