# Generated by Django 5.0.6 on 2025-12-17 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_vizier'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerentry',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('battle', 'Battle'), ('field_hospital', 'Field Hospital'), ('turmoil', 'Turmoil')], max_length=50),
        ),
        migrations.AlterField(
            model_name='officerentry',
            name='warrior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer', to='game.warrior'),
        ),
    ]
