# Generated by Django 5.0.6 on 2025-12-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_officerentry_used_alter_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wadaylight',
            name='step',
            field=models.CharField(choices=[('1', 'Actions'), ('4', 'Completed')], default='1', max_length=1),
        ),
    ]
