# Generated by Django 5.0.6 on 2026-02-26 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_battle_attacker_alter_battle_defender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='clearing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.clearing'),
        ),
        migrations.CreateModel(
            name='ExposureGuessedPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guessed_plot_type', models.CharField(choices=[('bomb', 'Bomb'), ('snare', 'Snare'), ('extortion', 'Extortion'), ('raid', 'Raid')], max_length=20)),
                ('turn_number', models.IntegerField(default=0)),
                ('clearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.clearing')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guessed_plots', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='ExposureRevealedCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revealed_cards', to='game.player')),
            ],
        ),
    ]
