# Generated by Django 5.0.6 on 2026-02-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_token_clearing_exposureguessedplot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowRaidEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crow_raid', to='game.event')),
                ('remaining_clearings', models.ManyToManyField(blank=True, to='game.clearing')),
            ],
        ),
    ]
