# Generated by Django 5.0.6 on 2025-12-18 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_wadaylight_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('battle', 'Battle'), ('field_hospital', 'Field Hospital'), ('turmoil', 'Turmoil'), ('outrage', 'Outrage')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wadaylight',
            name='step',
            field=models.CharField(choices=[('1', 'Actions'), ('2', 'Completed')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='OutrageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(choices=[('r', 'Fox'), ('y', 'Rabbit'), ('o', 'Mouse'), ('b', 'Bird')], max_length=1)),
                ('card_given', models.BooleanField(default=False)),
                ('hand_shown', models.BooleanField(default=False)),
                ('hand', models.JSONField(blank=True, default=dict, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outrage', to='game.event')),
                ('outraged_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outraged_events', to='game.player')),
                ('outrageous_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outrageous_events', to='game.player')),
            ],
        ),
    ]
