# Generated by Django 5.0.6 on 2025-12-19 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_event_type_alter_wadaylight_step_outrageevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldhospitalevent',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.event'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TurmoilEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_leader_chosen', models.BooleanField(default=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turmoil', to='game.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmoil', to='game.player')),
            ],
        ),
    ]
