# Generated by Django 5.0.6 on 2026-03-20 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_outrageevent_turn_number_alter_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('TURN', 'Turn'), ('PHASE', 'Phase'), ('MOVE', 'Move'), ('BATTLE', 'Battle'), ('CRAFT', 'Craft')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='game.game')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='game.gamelog')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
