# Generated by Django 5.0.6 on 2026-01-13 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_checkpoint_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldhospitalevent',
            name='player',
        ),
        migrations.RemoveField(
            model_name='fieldhospitalevent',
            name='troops_To_save',
        ),
        migrations.AlterField(
            model_name='fieldhospitalevent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_hospital', to='game.event'),
        ),
        migrations.AddField(
            model_name='fieldhospitalevent',
            name='troops_to_save',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
