# Generated by Django 5.0.6 on 2026-03-25 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_gamelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldhospitalevent',
            name='clearing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.clearing'),
        ),
        migrations.AlterField(
            model_name='gamelog',
            name='log_type',
            field=models.CharField(choices=[('TURN', 'Turn'), ('PHASE', 'Phase'), ('MOVE', 'Move'), ('BATTLE', 'Battle'), ('CRAFT', 'Craft'), ('DRAW', 'Draw'), ('DISCARD', 'Discard'), ('CATS_BIRDS_FOR_HIRE', 'Cats Birds for Hire'), ('CATS_MARCH', 'Cats March'), ('CATS_WOOD_PLACEMENT', 'Cats Wood Placement'), ('CATS_BUILD', 'Cats Build'), ('CATS_OVERWORK', 'Cats Overwork'), ('CATS_RECRUIT', 'Cats Recruit'), ('BIRDS_ADD_TO_DECREE', 'Birds Add To Decree'), ('BIRDS_EMERGENCY_ROOST', 'Birds Emergency Roost'), ('BIRDS_DECREE_ACTION', 'Birds Decree Action'), ('BIRDS_SCORE_ROOSTS', 'Birds Score Roosts'), ('BIRDS_TURMOIL', 'Birds Turmoil'), ('BIRDS_NEW_LEADER', 'Birds New Leader'), ('WA_REVOLT', 'Woodland Alliance Revolt'), ('WA_SPREAD_SYMPATHY', 'Woodland Alliance Spread Sympathy'), ('WA_MOBILIZE', 'Woodland Alliance Mobilize'), ('WA_TRAIN', 'Woodland Alliance Train'), ('WA_ORGANIZE', 'Woodland Alliance Organize'), ('WA_MILITARY_OPERATION', 'Woodland Alliance Military Operation'), ('CROWS_PLOT', 'Crows Plot'), ('CROWS_FLIP', 'Crows Flip'), ('CROWS_RECRUIT', 'Crows Recruit'), ('CROWS_TRICK', 'Crows Trick'), ('CROWS_EXPOSURE', 'Crows Exposure'), ('CROWS_RAID', 'Crows Raid'), ('WA_OUTRAGE', 'Outrage'), ('CATS_FIELD_HOSPITALS', 'Field Hospitals'), ('CRAFTED_CARD_ACTION', 'Crafted Card Action')], max_length=50),
        ),
    ]
