# Generated by Django 5.0.6 on 2026-01-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_fieldhospitalevent_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crafteditementry',
            name='exhausted',
            field=models.BooleanField(default=False),
        ),
    ]
