# Generated by Django 5.0.6 on 2026-01-14 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_fieldhospitalevent_player_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkpoint',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='checkpoint',
            name='unique_checkpoint_per_turn',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='turn_number',
        ),
        migrations.AddField(
            model_name='fieldhospitalevent',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
            preserve_default=False,
        ),
    ]
