# Generated by Django 5.0.6 on 2026-03-25 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_battle_log_alter_gamelog_log_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='log',
        ),
    ]
