# Generated by Django 5.0.6 on 2026-01-22 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_crafteditementry_exhausted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('battle', 'Battle'), ('field_hospital', 'Field Hospital'), ('turmoil', 'Turmoil'), ('outrage', 'Outrage'), ('informants', 'Informants')], max_length=50),
        ),
        migrations.CreateModel(
            name='InformantsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crafted_card_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informants_events', to='game.craftedcardentry')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informants', to='game.event')),
            ],
        ),
    ]
