# Generated by Django 5.0.6 on 2026-03-25 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_remove_battle_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='outrageevent',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gamelog'),
        ),
    ]
