# Generated by Django 5.0.6 on 2026-01-23 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_event_type_informantsevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyrieEmigreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_completed', models.BooleanField(default=False)),
                ('battle_initiated', models.BooleanField(default=False)),
                ('crafted_card_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eyrie_emigre_events', to='game.craftedcardentry')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eyrie_emigre', to='game.event')),
                ('move_destination', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eyrie_emigre_moves', to='game.clearing')),
            ],
        ),
    ]
