# Generated by Django 5.0.6 on 2026-03-25 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_outrageevent_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outrageevent',
            name='log',
        ),
        migrations.AddField(
            model_name='gamelog',
            name='outrage_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='game.outrageevent'),
        ),
    ]
