# Generated by Django 5.0.6 on 2026-01-27 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_eyrieemigreevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdbirdsong',
            name='step',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Emergency drawing'), ('2', 'Add to Decree'), ('3', 'Emergency roosting'), ('4', 'Completed')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='catbirdsong',
            name='step',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Place wood'), ('3', 'Completed')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('battle', 'Battle'), ('field_hospital', 'Field Hospital'), ('turmoil', 'Turmoil'), ('outrage', 'Outrage'), ('informants', 'Informants'), ('saboteurs', 'Saboteurs'), ('eyrie_emigre', 'Eyrie Emigre'), ('charm_offensive', 'Charm Offensive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wabirdsong',
            name='step',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Revolt'), ('2', 'Spread Sympathy'), ('3', 'Completed')], default='0', max_length=1),
        ),
        migrations.CreateModel(
            name='CharmOffensiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crafted_card_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charm_offensive_events', to='game.craftedcardentry')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charm_offensive', to='game.event')),
            ],
        ),
        migrations.CreateModel(
            name='SaboteursEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crafted_card_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saboteurs_events', to='game.craftedcardentry')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saboteurs', to='game.event')),
            ],
        ),
    ]
