# Generated by Django 5.0.6 on 2026-03-26 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_remove_outrageevent_log_gamelog_outrage_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='acting_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
        migrations.AlterField(
            model_name='gamelog',
            name='log_type',
            field=models.CharField(choices=[('TURN', 'Turn'), ('PHASE', 'Phase'), ('MOVE', 'Move'), ('BATTLE', 'Battle'), ('CRAFT', 'Craft'), ('DRAW', 'Draw'), ('DISCARD', 'Discard'), ('AMBUSH', 'Ambush'), ('DICE_ROLL', 'Dice Roll'), ('PIECE_REMOVAL', 'Piece Removal'), ('CATS_BIRDS_FOR_HIRE', 'Cats Birds for Hire'), ('CATS_MARCH', 'Cats March'), ('CATS_WOOD_PLACEMENT', 'Cats Wood Placement'), ('CATS_BUILD', 'Cats Build'), ('CATS_OVERWORK', 'Cats Overwork'), ('CATS_RECRUIT', 'Cats Recruit'), ('CATS_SETUP_PICK_CORNER', 'Cats Setup Pick Corner'), ('CATS_SETUP_PLACE_BUILDING', 'Cats Setup Place Building'), ('BIRDS_ADD_TO_DECREE', 'Birds Add To Decree'), ('BIRDS_EMERGENCY_ROOST', 'Birds Emergency Roost'), ('BIRDS_DECREE_ACTION', 'Birds Decree Action'), ('BIRDS_SCORE_ROOSTS', 'Birds Score Roosts'), ('BIRDS_TURMOIL', 'Birds Turmoil'), ('BIRDS_NEW_LEADER', 'Birds New Leader'), ('BIRDS_SETUP_PICK_CORNER', 'Birds Setup Pick Corner'), ('BIRDS_SETUP_CHOOSE_LEADER', 'Birds Setup Choose Leader'), ('WA_REVOLT', 'Woodland Revolt'), ('WA_SPREAD_SYMPATHY', 'Woodland Spread Sympathy'), ('WA_MOBILIZE', 'Woodland Mobilize'), ('WA_TRAIN', 'Woodland Train'), ('WA_ORGANIZE', 'Woodland Organize'), ('WA_MILITARY_OPERATION', 'Woodland Military Operation'), ('WA_OUTRAGE', 'Woodland Outrage'), ('WA_BASE_REMOVED', 'Woodland Base Removed'), ('WA_OFFICERS_LOST', 'Woodland Officers Lost'), ('WA_SUPPORTERS_LOST', 'Woodland Supporters Lost'), ('CROWS_PLOT', 'Crows Plot'), ('CROWS_FLIP', 'Crows Flip'), ('CROWS_RECRUIT', 'Crows Recruit'), ('CROWS_TRICK', 'Crows Trick'), ('CROWS_EXPOSURE', 'Crows Exposure'), ('CROWS_RAID', 'Crows Raid'), ('CROWS_SETUP_PLACE_WARRIOR', 'Crows Setup Place Warrior'), ('CROWS_EXTORTION_STOLE_CARD', 'Crows Extortion Stole Card'), ('CATS_FIELD_HOSPITALS', 'Field Hospitals'), ('CRAFTED_CARD_ACTION', 'Crafted Card Action')], max_length=50),
        ),
    ]
