# Generated by Django 5.0.6 on 2026-01-28 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_birdbirdsong_step_alter_catbirdsong_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('battle', 'Battle'), ('field_hospital', 'Field Hospital'), ('turmoil', 'Turmoil'), ('outrage', 'Outrage'), ('informants', 'Informants'), ('saboteurs', 'Saboteurs'), ('eyrie_emigre', 'Eyrie Emigre'), ('charm_offensive', 'Charm Offensive'), ('partisans', 'Partisans')], max_length=50),
        ),
        migrations.CreateModel(
            name='PartisansEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partisan_events', to='game.battle')),
                ('crafted_card_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partisan_events', to='game.craftedcardentry')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partisans', to='game.event')),
            ],
        ),
    ]
