# Generated by Django 5.0.6 on 2026-03-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_event_acting_player_alter_gamelog_log_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WarriorSupplyEntry',
        ),
    ]
