# Generated by Django 5.0.6 on 2026-01-28 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_event_type_partisansevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldhospitalevent',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_hospital_events', to='game.player'),
        ),
    ]
