# Generated by Django 5.0.6 on 2026-01-28 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_fieldhospitalevent_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffinWarrior',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.piece')),
            ],
            bases=('game.piece',),
        ),
    ]
