# Generated by Django 5.0.6 on 2026-03-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_delete_warriorsupplyentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='acting_player',
        ),
    ]
