# Generated by Django 5.0.6 on 2026-04-28 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_remove_event_acting_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citadel',
            fields=[
                ('building_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.building')),
                ('crafted_with', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('game.building', models.Model),
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('building_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.building')),
                ('crafted_with', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('game.building', models.Model),
        ),
        migrations.CreateModel(
            name='Tunnel',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.token')),
            ],
            bases=('game.token',),
        ),
        migrations.AlterField(
            model_name='birdbirdsong',
            name='step',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Emergency drawing'), ('2', 'Add to Decree'), ('3', 'Emergency roosting'), ('z', 'Before End'), ('4', 'Completed')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='birddaylight',
            name='step',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Crafting'), ('2', 'Recruiting'), ('3', 'Moving'), ('4', 'Battling'), ('5', 'Building'), ('z', 'Before End'), ('6', 'Completed'), ('a', 'Humiliate'), ('b', 'Purge'), ('c', 'Depose')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='birdevening',
            name='step',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Scoring'), ('2', 'Drawing Cards'), ('3', 'Discarding Cards'), ('z', 'Before End'), ('4', 'Completed')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='catbirdsong',
            name='step',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Place wood'), ('z', 'Before End'), ('3', 'Completed')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='catdaylight',
            name='step',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Crafting'), ('2', 'Actions'), ('z', 'Before End'), ('3', 'Completed')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='catevening',
            name='step',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Drawing Cards'), ('2', 'Discarding Cards'), ('z', 'Before End'), ('3', 'Completed')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='crowbirdsong',
            name='step',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Craft'), ('2', 'Flip'), ('3', 'Recruit'), ('z', 'Before End'), ('4', 'Completed')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='crowdaylight',
            name='step',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Actions'), ('z', 'Before End'), ('2', 'Completed')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='crowevening',
            name='step',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Exert'), ('2', 'Drawing'), ('3', 'Discarding'), ('z', 'Before End'), ('4', 'Completed')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='wabirdsong',
            name='step',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Revolt'), ('2', 'Spread Sympathy'), ('z', 'Before End'), ('3', 'Completed')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='wadaylight',
            name='step',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Actions'), ('z', 'Before End'), ('2', 'Completed')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='waevening',
            name='step',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Military Operations'), ('2', 'Drawing Cards'), ('3', 'Discarding Cards'), ('z', 'Before End'), ('4', 'Completed')], default='0', max_length=1),
        ),
        migrations.CreateModel(
            name='Burrow',
            fields=[
                ('clearing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.clearing')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='burrow', to='game.player')),
            ],
            bases=('game.clearing',),
        ),
        migrations.CreateModel(
            name='Crown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('squire', 'Squire'), ('noble', 'Noble'), ('lord', 'Lord')], default='squire', max_length=10)),
                ('used', models.BooleanField(default=False)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crown', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='RevealedCardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
    ]
