# Generated by Django 5.0.6 on 2026-04-28 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_citadel_market_tunnel_alter_birdbirdsong_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('marshal', 'Marshal'), ('captain', 'Captain'), ('foremole', 'Foremole'), ('brigadier', 'Brigadier'), ('mayor', 'Mayor'), ('banker', 'Banker'), ('duchess', 'Duchess of Mud'), ('earl', 'Earl of Stone'), ('baron', 'Baron of Dirt')], max_length=20)),
                ('swayed', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministers', to='game.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='minister',
            constraint=models.UniqueConstraint(fields=('player', 'name'), name='unique_minister_per_player'),
        ),
    ]
