# Generated by Django 5.0.6 on 2026-04-28 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_minister_minister_unique_minister_per_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoleTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveSmallIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='MoleEvening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('0', 'Not Started'), ('1', 'Process Revealed Cards'), ('2', 'Craft'), ('3', 'Draw'), ('4', 'Discard'), ('z', 'Before End'), ('5', 'Completed')], default='0', max_length=1)),
                ('cards_drawn', models.IntegerField(default=0)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evening', to='game.moleturn')),
            ],
        ),
        migrations.CreateModel(
            name='MoleDaylight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('0', 'Not Started'), ('1', 'Actions'), ('2', 'Minister Actions'), ('3', 'Sway Minister'), ('z', 'Before End'), ('4', 'Completed')], default='0', max_length=1)),
                ('actions_remaining', models.IntegerField(default=0)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daylight', to='game.moleturn')),
            ],
        ),
        migrations.CreateModel(
            name='MoleBirdsong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('0', 'Not Started'), ('1', 'Place Warriors'), ('z', 'Before End'), ('2', 'Completed')], default='0', max_length=1)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birdsong', to='game.moleturn')),
            ],
        ),
    ]
