# Generated by Django 5.0.6 on 2026-04-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_moleturn_moleevening_moledaylight_molebirdsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='attacker',
            field=models.CharField(choices=[('ca', 'Cats'), ('bi', 'Birds'), ('wa', 'Woodland Alliance'), ('cr', 'Crows'), ('mo', 'Moles')], max_length=2),
        ),
        migrations.AlterField(
            model_name='battle',
            name='defender',
            field=models.CharField(choices=[('ca', 'Cats'), ('bi', 'Birds'), ('wa', 'Woodland Alliance'), ('cr', 'Crows'), ('mo', 'Moles')], max_length=2),
        ),
        migrations.AlterField(
            model_name='factionchoiceentry',
            name='faction',
            field=models.CharField(choices=[('ca', 'Cats'), ('bi', 'Birds'), ('wa', 'Woodland Alliance'), ('cr', 'Crows'), ('mo', 'Moles')], max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='faction',
            field=models.CharField(blank=True, choices=[('ca', 'Cats'), ('bi', 'Birds'), ('wa', 'Woodland Alliance'), ('cr', 'Crows'), ('mo', 'Moles')], max_length=2, null=True),
        ),
    ]
