# Generated by Django 5.0.6 on 2026-04-28 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_alter_battle_attacker_alter_battle_defender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesimplesetup',
            name='status',
            field=models.CharField(choices=[('INIT', 'Initial Setup'), ('CAT', 'Cats Setup'), ('BIRD', 'Birds Setup'), ('WA', 'Woodland Alliance Setup'), ('VB', 'Vagabond Setup'), ('CROW', 'Crows Setup'), ('MOL', 'Moles Setup'), ('COMP', 'Completed')], default='INIT', max_length=4),
        ),
        migrations.CreateModel(
            name='MolesSimpleSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('1', 'Picking Corner'), ('2', 'Pending Confirmation'), ('3', 'Completed')], default='1', max_length=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='molessimplesetup',
            constraint=models.UniqueConstraint(fields=('player',), name='unique_moles_setup_per_player'),
        ),
    ]
