# Generated by Django 5.0.6 on 2026-04-29 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_gamesimplesetup_status_molessimplesetup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moledaylight',
            name='actions_remaining',
        ),
        migrations.AddField(
            model_name='moledaylight',
            name='actions_left',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='moledaylight',
            name='brigadier_action',
            field=models.CharField(choices=[('none', 'None'), ('battle', 'Battle'), ('move', 'Move')], default='none', max_length=6),
        ),
        migrations.AlterField(
            model_name='crown',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowns', to='game.player'),
        ),
    ]
