# Generated by Django 5.0.6 on 2026-05-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_alter_event_type_alter_gamelog_log_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revealedcardentry',
            name='returned_to_hand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revealedcardentry',
            name='turn_revealed',
            field=models.IntegerField(default=0),
        ),
    ]
